version: "3"
services: 
  web: 
    build: .
    ports: 
      - "9000:8080"
    environment: 
      - NODE_ENV=staging
      - MONGODB_URL=mongodb://mongo:27017/superhero
    links: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017"