version: "3"
services: 
  web: 
    build: .
    ports: 
      - "3008:8080"
    environment: 
      - NODE_ENV=staging
      - PORT=8080
      - MONGODB_URL=mongodb://mongo:27017/superhero
    links: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017"