version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    working_directory: ~/superhero-connect
    steps:
      - checkout
      - run: yarn install
      # - run:
      #     - name: Build Typescript
      #     - command: yarn run build:tsc >> /tmp/logs/tsc-build-logs 2>&1
      # - run:
      #     - name: Run Tests
      #     - command: yarn test >> /tmp/logs/test-logs 2>&1
